### ISSUE TITLE
Modifying state during view update, this will cause undefined behavior

### ISSUE THREAD

**Issue by AndrewLipscomb** [edw/swiftui-numberfield#1]
So I've been following the same trail as you I think - https://stackoverflow.com/questions/58178825/swiftui-validation-and-vetoing-for-user-input is my one for the generic version of this question (any sort of input event -> validate -> rerender cycle) 

As you probably know - the `Modifying state during view update, this will cause undefined behavior` message pops up for all the versions of this type of solution. My question is - does this actually cause issues? This seems like the cleanest solution apart from that warning. 

And if you know - how else are you meant to actually modify `@State` types? You can't do it inside the `body` according to the message, and accessing it outside also causes warnings or errors.

**Comment by edw** [comment]
I've been bumping up against these sorts of warnings in this and other situations. It's frustrating to not know whether one's code has problems or if it's SwiftUI acting up. I encourage people to never blame the compiler (or the library, or …) but in this case I'm taking a wait and see approach.

**Comment by edw** [comment]
I fixed this for now in 3342f63268f5435cc00f286ad31709a9f60dfb7a by wrapping the mutation in a `DispatchQueue.main.async { … }` call.
